spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:develop}
  application:
    name: tech-challenge-users-api
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
      type: trace
      use_sql_comments: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    hikari:
      maximum-pool-size: 30
      connection-timeout: 24000
      minimum-idle: 10
    driver-class-name: org.postgresql.Driver
  # Configurações do Flyway para migrações automáticas
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
    clean-disabled: true
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    placeholder-replacement: true
    placeholders:
      schema: tech_challenge
  security:
    jwt:
      secret: '6d95243a-674f-4bc1-b0f0-b7aa470c8ffb'
      expiration-time: 86400000
server:
  port: ${APP_PORT:8080}
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    defaults:
      enabled: true
    db:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus,metrics-requiredMetricName,metrics,health-path,health,info

default:
  cors:
    allowed:
      origin: http://localhost:8080,http://localhost:3000,http://*:3000,http://*:8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.flywaydb: INFO

---
spring:
  config:
    activate:
      on-profile: develop
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_SCHEMA:tech_challenge}
    username: ${BD_USER:postgres}
    password: ${BD_PASS:root}
  jpa:
    show-sql: true
  flyway:
    enabled: true

logging:
  level:
    com.fiap.itmoura.tech_challenge: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://fiap-postgres:5432/tech_challenge
    username: ${BD_USER:postgres}
    password: ${BD_PASS:root}
  jpa:
    show-sql: false
  flyway:
    enabled: true

logging:
  level:
    com.fiap.itmoura.tech_challenge: INFO
    org.flywaydb: INFO

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  flyway:
    enabled: false  # Desabilita Flyway nos testes para usar H2 em memória

logging:
  level:
    com.fiap.itmoura.tech_challenge: DEBUG

